baseURL = "https://sabs-r3.github.io/"
languageCode = "en-us"
title = "SABS:R<sup>3</sup>"
copyright = "Oxford"
theme = "serif"

[params]
google_analytics_id=""

[[menu.main]]
name = "About"
url = "/program/"
weight = 1

[[menu.main]]
name = "Apply"
url = "/apply/"
weight = 2

[[menu.main]]
name = "Team"
url = "/team/"
weight = 3

[[menu.main]]
name = "Modules 2019"
url = "/modules/"
weight = 4

[[menu.main]]
name = "Example Projects"
url = "/projects/"
weight = 5

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 6
